server:
  port: 8080
  
  spring:
  datasource:
    username: root
    password: 123456789
    url: jdbc:h2:mem:employeemgtdb
   
    jpa:
    show-sql: true
    hibernate:
       ddl-auto: create